### ISSUE TITLE
"Could not find imported module support code for ibmi_cl_command.  Looked for either ibmi_util.py or ibmi.py

### ISSUE THREAD

**Issue by ChennaiTechie** [IBM/cloud-i-blog#2]
Hello Team,

Am running ansible from centos ... Ping pong to IBM I Lpar is sucessfull where when i run the model i get the above error. 

 ansible ibmi -i hosts -M /home/ansible/ansible-for-i/plugins/module_utils/ibmi -m ibmi_cl_command -a "cmd='crtlib lib(C1)'"

--------------------------------------------------
172.16.120.70 | FAILED! => {
    "msg": "Could not find imported module support code for ibmi_cl_command.  Looked for either ibmi_util.py or ibmi.py"
}

**Comment by changlexc** [comment]
ansible  —version command will show the module search path, you need to copy the ibmi modules under it. If you want to configure your own module search path, it should be write in ansible.cfg, see readme and sample for more about the enable ansible on ibmi.

**Comment by changlexc** [comment]
One more, The ibmi/* under module_utils dir also need to copy to the ansible run time dir.

**Comment by ChennaiTechie** [comment]
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
-----------------------------------------------------------------------
i have copied all the files (*.py) from ansible-for-i/plugins/modules to /usr/share/ansible/plugins/modules 
-------------------------------------------------------------------------
I have also copied the *.py files under folder ibmi to /usr/share/ansible/plugins/module_utils
----------------------------------------------------------------------------
Still i get the below error 

[ansible@localhost ~]$ ansible-playbook -i hosts crtlib.yml

PLAY [ibmi] *********************************************************************************************************************************************************************************

TASK [run the CL command to create a library] ***********************************************************************************************************************************************
fatal: [172.16.120.70]: FAILED! => {"msg": "Could not find imported module support code for ibmi_cl_command.  Looked for either ibmi_util.py or ibmi.py"}
...ignoring

PLAY RECAP **********************************************************************************************************************************************************************************
172.16.120.70              : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1

**Comment by changlexc** [comment]
I think the ansible-for-i-development/lib/ansible/modules/ibmi/*.py should be copied to 
ansible python module location = /usr/lib/python3.6/site-packages/ansible

For example, on my system 
changlecBookPro:ansible changle$ ansible --version
ansible 2.9.5
  config file = /Users/changle/.ansible.cfg
  configured module search path = ['**/Users/changle/git/ansible/lib/ansible/modules**']
  ansible python module location = **/Library/Python/3.7/site-packages/ansible**
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Nov 15 2019, 04:04:52) [Clang 11.0.0 (clang-1100.0.33.16)]

I have the following copy commands when I get the code from git to my system,
1 . ----------
cp /Users/changle/git/ansible-for-i-development/lib/ansible/modules/ibmi/* ~/git/ansible/lib/ansible/modules/ibmi/
2 . ----------
sudo cp /Users/changle/git/ansible-for-i-development/lib/ansible/module_utils/ibmi/* /Library/Python/3.7/site-packages/ansible/module_utils/ibmi/

**Comment by changlexc** [comment]
I think the ansible-for-i-development/lib/ansible/module_utils/ibmi/*  should be copied to
ansible python module location = /usr/lib/python3.6/site-packages/ansible. Sorry for my last comments for unclear word 'run time'.

For example, on my system
changlecBookPro:ansible changle$ ansible --version
ansible 2.9.5
config file = /Users/changle/.ansible.cfg
configured module search path = ['/Users/changle/git/ansible/lib/ansible/modules']
ansible python module location = /Library/Python/3.7/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.7.3 (default, Nov 15 2019, 04:04:52) [Clang 11.0.0 (clang-1100.0.33.16)]

I have the following copy commands when I get the code from git to my system,
1 . ----------
cp /Users/changle/git/ansible-for-i-development/lib/ansible/modules/ibmi/* ~/git/ansible/lib/ansible/modules/ibmi/
2 . ----------
sudo cp /Users/changle/git/ansible-for-i-development/lib/ansible/module_utils/ibmi/* /Library/Python/3.7/site-packages/ansible/module_utils/ibmi/

**Comment by ChennaiTechie** [comment]
Hello,

I really appreciate your assistance , I was able to fix the issue thanks for your time.
